### ISSUE TITLE
Sign in with Google fails when running locally

### ISSUE THREAD

**Issue by elft3r** [kart7990/virtualpitwall#2]
Hey,
I was trying out the code and wanted to run it locally. I started the `development.env` setting with `npm start`. However, when I want to Sign in, using my Google Account, I get the following error message:
<img width="1178" alt="Screenshot 2023-12-22 at 12 29 36" src="https://github.com/kart7990/virtualpitwall/assets/2915576/779aa6a2-242f-4c2b-ac54-3f28cb4cb96c">

Looking at the network calls, I see the following error message:
<img width="1474" alt="Screenshot 2023-12-22 at 12 34 44" src="https://github.com/kart7990/virtualpitwall/assets/2915576/f2c5b97d-505b-4417-8bdd-6ca4a59e81e3">

Would you happen to know what's wrong and what I need to do to make this work?

Thanks for your help,
Jochen

**Comment by kart7990** [comment]
The database needs to wake up. It goes to sleep after 1 hour of inactivity.
Should take less than a minute to spin up after the first request.
Eventually I'll move it off the low tier offering.

Also, I've got the itch to develop this a bit more. Working on a V2
version, branch is v2/shadcnui.

David

**Comment by elft3r** [comment]
Hey David,
thanks for your reply. I tried it again, with some waiting period to give the DB time to wake up. But I still get the same error. Could it be, that I first need to register, or should the login do that automatically for me? If so, what would be the way to register?

I'm new to the app and just saw your announcement, that you open-sourced it and wanted to give it a try and see if I can support it in any way.

> Also, I've got the itch to develop this a bit more. Working on a V2
version, branch is v2/shadcnui.

I will have a look and give it a try.

Best,
Jochen

**Comment by kart7990** [comment]
Ah, yeah the wrong google oauth client id was being used which doesn't allow for localhost origins. I just pushed a change to use the dev/test oauth client id.

**Comment by kart7990** [comment]
Changes have been deployed and smoke test looks good.

**Comment by elft3r** [comment]
Thanks David, the changes worked and I'm now able to login when running the app locally.

I will now explore the app and also have a look at the v2 branch to see how I can contribute to it.
